backend:
  name: git-gateway
  repo: kurukururuu/simple-gallery
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts
# local_backend: true # For local testing

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "select", options: ["audio", "video"] }
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Authors", name: "authors", widget: "relation", collection: "author", search_fields: ["name"], value_field: "name", display_fields: ["name"], multiple: true}
      - {label: "Categories", name: "categories", widget: "list", allow_add: true, add_to_top: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "author"
    label: "Author"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "Body", name: "body", widget: "markdown"}

